const { promises: fs } = require('node:fs')
const path = require('node:path')

/**
 * Chromium's sandbox cannot work inside an AppImage: the FUSE mount is
 * nosuid (so the SUID chrome-sandbox helper never works) and Ubuntu 23.10+
 * blocks the user-namespace fallback via AppArmor. The AppImage's AppRun
 * is generated by electron-builder's native app-builder binary and only
 * passes through the CLI args it receives, so a double-click launch never
 * gets --no-sandbox.
 *
 * Solution: rename the packaged binary to `<name>.bin` and put a tiny
 * wrapper script at the original name that execs it with --no-sandbox.
 * electron-builder's linux.executableArgs only fixes the .desktop Exec
 * line; this wrapper fixes every launch method (double-click, CLI, menu).
 */
exports.default = async function afterPack(context) {
  const { electronPlatformName, appOutDir, packager } = context
  if (electronPlatformName !== 'linux') return

  const executableName = packager.executableName
  const bin = path.join(appOutDir, executableName)
  const binReal = `${bin}.bin`

  try {
    const stat = await fs.stat(bin)
    if (!stat.isFile()) return
  } catch {
    console.warn(`[afterPack] ${executableName} not found, skipping sandbox wrapper`)
    return
  }

  await fs.rename(bin, binReal)

  const wrapper = `#!/bin/sh
# Chromium's SUID sandbox cannot work inside an AppImage (nosuid FUSE mount)
# and Ubuntu 23.10+ restricts the user-namespace fallback via AppArmor.
# --no-sandbox is the documented workaround; the real binary is ${executableName}.bin
exec "$(dirname "$(readlink -f "$0")")/${executableName}.bin" --no-sandbox "$@"
`
  await fs.writeFile(bin, wrapper, { mode: 0o755 })
  console.log(`[afterPack] Wrapped ${executableName} with --no-sandbox`)
}
